---
title: "PCA"
output: html_notebook
author: Johannes Bjork
---

```{r load packages}
require(tidyverse)
require(patchwork)
```

```{r load data}
food_freqs_uk <- readRDS("~/food_freqs_uk.rds")
food_freqs_nl <- readRDS("~/food_freqs_nl.rds")
```

```{r PCA}
pca_uk <- prcomp(food_freqs_uk, scale = TRUE)
pca_nl <- prcomp(food_freqs_nl, scale = TRUE)
```

```{r plot biplots}
p1_uk <- 
  ggplot() +
  
  # Feature loadings
  geom_segment(data=(data.frame(pca_uk$rotation) %>%
                     rownames_to_column("feature_id") %>% 
                     mutate(feature_id_num=factor(feature_id, levels=unique(feature_id), labels=paste(1:23,feature_id)),
                            PC1=PC1*7, PC2=PC2*7)),
               aes(x=0, xend=PC1, y=0, yend=PC2, color=feature_id_num), 
               arrow=arrow(length=unit(0.3,"cm"))) + 
  
  geom_text(data=(data.frame(pca_uk$rotation) %>%
                    rownames_to_column("feature_id") %>% 
                    mutate(feature_id_num=factor(feature_id, levels=unique(feature_id), labels=1:23),
                           PC1=PC1*7, PC2=PC2*7)), 
            aes(x=PC1, y=PC2, label=feature_id_num), 
            nudge_x=0.03,
            nudge_y=0) +
  
  # Sample loadings
  geom_point(data=data.frame(pca_uk$x),
             aes(x=PC1, y=PC2), size=2) +
  
  scale_color_manual(values=rep("black",23)) +
  guides(colour=guide_legend(ncol=1)) +
  
  theme(
    legend.title = element_blank(),
    legend.key=element_rect(fill='white'),
    panel.grid.major=element_blank(), 
    panel.grid.minor=element_blank(), 
    panel.background=element_rect(fill="white"),
    panel.border=element_rect(colour="black", fill=NA, size=1),
    axis.ticks.length=unit(0.10,"cm"), 
    axis.text.x=element_text(size=12, color="black",hjust=0.95,vjust=0.2),
    axis.text.y=element_text(size=12, color="black"),
    axis.title=element_text(size=15, color="black")) +
  labs(x=paste0("PC1 (", round((summary(pca_uk)$importance[2,1:2]*100))[1],"%)"), y=paste0("PC2 (", round((summary(pca_uk)$importance[2,1:2]*100))[2],"%)"))


p1_nl <- 
  ggplot() +
  
  # Feature loadings
  geom_segment(data=(data.frame(pca_nl$rotation) %>%
                     rownames_to_column("feature_id") %>% 
                     mutate(feature_id_num=factor(feature_id, levels=unique(feature_id), labels=paste(1:17,feature_id)),
                            PC1=PC1*7, PC2=PC2*7)),
               aes(x=0, xend=PC1, y=0, yend=PC2, color=feature_id_num), 
               arrow=arrow(length=unit(0.3,"cm"))) + 
  
  geom_text(data=(data.frame(pca_nl$rotation) %>%
                    rownames_to_column("feature_id") %>% 
                    mutate(feature_id_num=factor(feature_id, levels=unique(feature_id), labels=1:17),
                           PC1=PC1*7, PC2=PC2*7)), 
            aes(x=PC1, y=PC2, label=feature_id_num), 
            nudge_x=0.03,
            nudge_y=0) +
  
  # Sample loadings
  geom_point(data=data.frame(pca_nl$x),
             aes(x=PC1, y=PC2), size=2) +
  
  scale_color_manual(values=rep("black",23)) +
  guides(colour=guide_legend(ncol=1)) +
  
  theme(
    legend.title = element_blank(),
    legend.key=element_rect(fill='white'),
    panel.grid.major=element_blank(), 
    panel.grid.minor=element_blank(), 
    panel.background=element_rect(fill="white"),
    panel.border=element_rect(colour="black", fill=NA, size=1),
    axis.ticks.length=unit(0.10,"cm"), 
    axis.text.x=element_text(size=12, color="black",hjust=0.95,vjust=0.2),
    axis.text.y=element_text(size=12, color="black"),
    axis.title=element_text(size=15, color="black")) +
  labs(x=paste0("PC1 (", round((summary(pca_nl)$importance[2,1:2]*100))[1],"%)"), y=paste0("PC2 (", round((summary(pca_nl)$importance[2,1:2]*100))[2],"%)"))

p1_uk + p1_nl

```

```{r plot heatmaps}
# Heatmaps displaying which diet correlates more strongly with each PC 
p2_uk <- 
  data.frame(t(t(pca_uk$rotation) * sqrt(pca_uk$sdev^2))) %>% 
  rownames_to_column("feature_id") %>% 
  select(feature_id, PC1, PC2, PC3, PC4, PC5) %>% 
  mutate(feature_id=fct_reorder(feature_id, PC1, max)) %>% 
  pivot_longer(!feature_id, names_to="PCs", values_to="value") %>%
  ggplot(aes(y=feature_id, x=PCs, fill=value)) +
  geom_tile() +
  scale_fill_gradient2(high="red", mid="white", low="blue", breaks=seq(from=-1, to=1, by=0.5)) +
  theme(
    legend.text=element_text(size=12, color="black"),
    legend.title = element_blank(),
    legend.key=element_rect(fill='white'),
    panel.grid.major=element_blank(), 
    panel.grid.minor=element_blank(), 
    panel.background=element_rect(fill="white"),
    panel.border=element_rect(colour="black", fill=NA, size=1),
    axis.ticks.length=unit(0.10,"cm"), 
    axis.text.x=element_text(size=10, color="black"),
    axis.text.y=element_text(size=13, color="black"),
    axis.title=element_text(size=15, color="black")) +
  labs(y=NULL)

p2_nl <- 
  data.frame(t(t(pca_nl$rotation) * sqrt(pca_nl$sdev^2))) %>% 
  rownames_to_column("feature_id") %>% 
  select(feature_id, PC1, PC2, PC3, PC4, PC5) %>% 
  mutate(feature_id=fct_reorder(feature_id, PC1, max)) %>% 
  pivot_longer(!feature_id, names_to="PCs", values_to="value") %>%
  ggplot(aes(y=feature_id, x=PCs, fill=value)) +
  geom_tile() +
  scale_fill_gradient2(high="red", mid="white", low="blue", breaks=seq(from=-1, to=1, by=0.5)) +
  theme(
    legend.text=element_text(size=12, color="black"),
    legend.title = element_blank(),
    legend.key=element_rect(fill='white'),
    panel.grid.major=element_blank(), 
    panel.grid.minor=element_blank(), 
    panel.background=element_rect(fill="white"),
    panel.border=element_rect(colour="black", fill=NA, size=1),
    axis.ticks.length=unit(0.10,"cm"), 
    axis.text.x=element_text(size=10, color="black"),
    axis.text.y=element_text(size=13, color="black"),
    axis.title=element_text(size=15, color="black")) +
  labs(y=NULL)

p2_uk + p2_nl + plot_layout(guides = "collect")
```
